Repository openshift/kedacore-keda, pull requests merged in 2024-03, with the labels that each got.

#23 UPSTREAM: 5595: Add more granular control to E2E test setup
  CHANGELOG.md
  tests/helper/helper.go
  tests/utils/cleanup_test.go
  tests/utils/setup_test.go
Labels: lgtm, approved

#25 OCPBUGS-30725: bump go-jose/v3 to 3.0.3 to fix CVE-2024-28180
  go.mod
  go.sum
  vendor/github.com/go-jose/go-jose/v3/BUG-BOUNTY.md
  vendor/github.com/go-jose/go-jose/v3/CHANGELOG.md
  vendor/github.com/go-jose/go-jose/v3/README.md
  vendor/github.com/go-jose/go-jose/v3/SECURITY.md
  vendor/github.com/go-jose/go-jose/v3/asymmetric.go
  vendor/github.com/go-jose/go-jose/v3/crypter.go
  vendor/github.com/go-jose/go-jose/v3/doc.go
  vendor/github.com/go-jose/go-jose/v3/encoding.go
  vendor/github.com/go-jose/go-jose/v3/json/decode.go
  vendor/github.com/go-jose/go-jose/v3/json/encode.go
  vendor/github.com/go-jose/go-jose/v3/json/stream.go
  vendor/github.com/go-jose/go-jose/v3/jwe.go
  vendor/github.com/go-jose/go-jose/v3/jwk.go
  vendor/github.com/go-jose/go-jose/v3/jws.go
  vendor/github.com/go-jose/go-jose/v3/jwt/claims.go
  vendor/github.com/go-jose/go-jose/v3/jwt/doc.go
  vendor/github.com/go-jose/go-jose/v3/opaque.go
  vendor/github.com/go-jose/go-jose/v3/shared.go
  vendor/github.com/go-jose/go-jose/v3/signing.go
  vendor/github.com/go-jose/go-jose/v3/symmetric.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#26 OCPBUGS-30145: fix: Prevented memory leak generated by not correctly cleaned HTTP resources (#5293)
  CHANGELOG.md
  pkg/scalers/activemq_scaler.go
  pkg/scalers/artemis_scaler.go
  pkg/scalers/azure_blob_scaler.go
  pkg/scalers/azure_data_explorer_scaler.go
  pkg/scalers/azure_log_analytics_scaler.go
  pkg/scalers/azure_pipelines_scaler.go
  pkg/scalers/azure_queue_scaler.go
  pkg/scalers/cassandra_scaler.go
  pkg/scalers/datadog_scaler.go
  pkg/scalers/github_runner_scaler.go
  pkg/scalers/graphite_scaler.go
  pkg/scalers/loki_scaler.go
  pkg/scalers/metrics_api_scaler.go
  pkg/scalers/metrics_api_scaler_test.go
  pkg/scalers/nats_jetstream_scaler.go
  pkg/scalers/openstack_metrics_scaler.go
  pkg/scalers/openstack_swift_scaler.go
  pkg/scalers/openstack_swift_scaler_test.go
  pkg/scalers/prometheus_scaler.go
  pkg/scalers/pulsar_scaler.go
  pkg/scalers/rabbitmq_scaler.go
  pkg/scalers/selenium_grid_scaler.go
  pkg/scalers/solace_scaler.go
  pkg/scalers/solr_scaler.go
  pkg/scalers/stan_scaler.go
  pkg/util/certificates.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference
